[package]
name = "common"
version = "0.1.0"
edition = "2021"

[dependencies]
chrono = { version = "0.4.38", features = ["serde"] }
rand = "0.9.0-alpha.2"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0.132"
toml = "0.8.19"